### ISSUE TITLE
Remove .DS_Store

### ISSUE THREAD

**Issue by TommyRed** [monarezio/task-manager-java#1]
Self explanatory

**Comment by monarezio** [comment]
Fixed in #e2bdec7

**Comment by monarezio** [comment]
Fixed in #e2bdec77fe9ede18de0b06591c5d97b987510938

**Comment by monarezio** [comment]
Fixed in https://github.com/monarezio/task-manager-java/commit/e2bdec77fe9ede18de0b06591c5d97b987510938

**Comment by TommyRed** [comment]
Is it, tho?
